// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-Kfzw5bTeeic5VGZo2vLdO_irt54xs4',
    appId: '1:96984675131:web:a7f2080aea0bee4f29bd1e',
    messagingSenderId: '96984675131',
    projectId: 'evently-app-ce32d',
    authDomain: 'evently-app-ce32d.firebaseapp.com',
    storageBucket: 'evently-app-ce32d.firebasestorage.app',
    measurementId: 'G-M5QX0NE3WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8vs2YKweuZKZQ4cnj3burZRI-4F9wXs8',
    appId: '1:96984675131:android:aabcc3d029b6797229bd1e',
    messagingSenderId: '96984675131',
    projectId: 'evently-app-ce32d',
    storageBucket: 'evently-app-ce32d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfw4CfNRL8cjN5KyRs2mnPILX3qg0NqFI',
    appId: '1:96984675131:ios:6a8e96890db18b0a29bd1e',
    messagingSenderId: '96984675131',
    projectId: 'evently-app-ce32d',
    storageBucket: 'evently-app-ce32d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfw4CfNRL8cjN5KyRs2mnPILX3qg0NqFI',
    appId: '1:96984675131:ios:6a8e96890db18b0a29bd1e',
    messagingSenderId: '96984675131',
    projectId: 'evently-app-ce32d',
    storageBucket: 'evently-app-ce32d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg-Kfzw5bTeeic5VGZo2vLdO_irt54xs4',
    appId: '1:96984675131:web:d6a1b37204366e5e29bd1e',
    messagingSenderId: '96984675131',
    projectId: 'evently-app-ce32d',
    authDomain: 'evently-app-ce32d.firebaseapp.com',
    storageBucket: 'evently-app-ce32d.firebasestorage.app',
    measurementId: 'G-DN9MSJZT4G',
  );
}
